# Generated by Django 4.0.1 on 2022-01-21 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Migrations são criadas automaticamente através do comando python manage.py makemigrations <nomeDoApp>
# Para executar as migrations, utilizar o comando python manage.py migrate <nomeDoApp>
# Outros comandos relacionados à migrations:
#   python manage.py sqlmigrate <nomeDoApp> <indexDaMigration> --> Indica o comando SQL que será executado ao rodar a migration indicada
#   python manage.py showmigrations <nomeDoApp:opcional> --> Indica o status das migrations do app indicado (caso não seja indicado um app, mostra de todos)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
